name: 'boating_accident_data'
version: '1.0.0'

profile: 'boating_accident_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  boating_accident_data:
    staging:
      +materialized: view
